.\"	$Id: mrstat.1,v 1.2 2002/08/14 15:19:13 abs Exp $
.\"
.\" Copyright (c) 2002 by David Brownlee <abs@absd.org>
.\" Absolutely no warranty.
.\"
.Dd Aug 13, 2002
.Dt MRSTAT 1
.Sh NAME
.Nm mrstat
.Nd Track load, uptime, and number of users on specified hosts
.Sh SYNOPSIS
.Nm
.Op Ar args
.Sh DESCRIPTION
Would be here...
Run
.Nm
.Ar -h
for more information.
.Sh AUTHORS
David Brownlee <abs@absd.org>.
